AWSTemplateFormatVersion: "2010-09-09"
Description: A sample EC2 template
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-077e31c4939f6a2f3"
      InstanceType:
        Ref: InstanceTypeParameter
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          GroupSet:
            - !Ref myVPCEC2SecurityGroup
          SubnetId: !Ref PublicSubnet

  myVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: "10.1.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default

  myVPCEC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Public instance security group
      VpcId: !Ref myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: "10.1.0.0/24"
      VpcId: !Ref myVPC

Outputs:
  InstanceID:
    Description: The Instance ID
    Value: !Ref MyEC2Instance
  InstanceIP:
    Description: The instance public IP
    Value: !GetAtt [ MyEC2Instance, PublicIp ]
